# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Set up and build React app
      run: |
            touch .env
            echo REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }} >> .env
            echo REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} >> .env
            echo REACT_APP_GOOGLE_SECRET=${{ secrets.REACT_APP_GOOGLE_SECRET }} >> .env
            echo REACT_APP_CLOUDINARY_API_KEY=${{ secrets.REACT_APP_CLOUDINARY_API_KEY }} >> .env
            echo REACT_APP_CLOUDINARY_CLOUD_NAME=${{ secrets.REACT_APP_CLOUDINARY_CLOUD_NAME }} >> .env
            echo REACT_APP_CLOUDINARY_PRESET=${{ secrets.REACT_APP_CLOUDINARY_PRESET }} >> .env
            cat .env
    - name: Build
      run: |
            npm install ---force
            npm run build
    - name: Firebase Deploy 
      run: |
            sudo npm install -g firebase-tools
            firebase deploy --token ${{ secrets.FIREBASE_TOKEN}}